// Generated from: e2e/peerchat.feature
import { test } from "../../e2e/fixtures/index.ts";

test.describe('PeerChat – Serverless P2P Chat', () => {

  test.beforeEach('Background', async ({ Given, world }, testInfo) => { if (testInfo.error) return;
    await Given('the PeerChat application is running at "http://localhost:5174"', null, { world }); 
  });
  
  test('Landing page renders correctly', async ({ Then, And, world }) => { 
    await Then('I see the "PeerChat" heading', null, { world }); 
    await And('I see the tagline "Serverless, private, ephemeral."', null, { world }); 
    await And('I see a "Join a Room" section with a 4-digit code input', null, { world }); 
    await And('I see a "Host a Room" section with an arrow button', null, { world }); 
    await And('the "Join Room" button is disabled', null, { world }); 
    await And('I see the footer "Powered by PeerJS • End-to-End Client Side"', null, { world }); 
  });

  test('Join button enables only when 4 characters are typed', async ({ When, Then, world }) => { 
    await When('I type "12" in the room code input', null, { world }); 
    await Then('the "Join Room" button is disabled', null, { world }); 
    await When('I type "1234" in the room code input', null, { world }); 
    await Then('the "Join Room" button is enabled', null, { world }); 
  });

  test('Input enforces maximum length of 4 characters', async ({ When, Then, And, world }) => { 
    await When('I type "12345" in the room code input', null, { world }); 
    await Then('the input value is "1234"', null, { world }); 
    await And('the "Join Room" button is enabled', null, { world }); 
  });

  test('Host creates a room and receives a room code', async ({ When, Then, And, world }) => { 
    await When('I click "Host a Room"', null, { world }); 
    await Then('I am taken to the chat room view', null, { world }); 
    await And('I see a 4-digit room code in the sidebar', null, { world }); 
    await And('I see "1 ACTIVE USERS" in the header', null, { world }); 
    await And('my username is listed with "(You)" label in the sidebar', null, { world }); 
    await And('I see a "Start Call" button', null, { world }); 
    await And('I see the footer "End-to-End Encrypted P2P Connection"', null, { world }); 
  });

  test('Host leaves the room and returns to the landing page', async ({ Given, When, Then, And, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I click "Leave Room"', null, { world }); 
    await Then('I am returned to the landing page', null, { world }); 
    await And('I see the "PeerChat" heading', null, { world }); 
  });

  test('Host renames the room and the change propagates to the guest', async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host clicks the room name edit icon in the sidebar', null, { world }); 
    await And('the host clears the field and types "Sala de Testes E2E"', null, { world }); 
    await And('the host presses Enter', null, { world }); 
    await Then('the host sees "Sala de Testes E2E" as the room name in the sidebar and header', null, { world }); 
    await And('the guest also sees "Sala de Testes E2E" as the room name in real-time', null, { world }); 
  });

  test('Host cannot join another room while already hosting', async ({ Given, Then, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await Then('there is no room code input visible on the screen', null, { world }); 
  });

  test('Guest joins an existing room with a valid code', async ({ Given, When, Then, And, world }) => { 
    await Given('a host has created a room with code "8414"', null, { world }); 
    await And('I am on the landing page as a guest', null, { world }); 
    await When('I type "8414" in the room code input', null, { world }); 
    await And('I click "Join Room"', null, { world }); 
    await Then('I am taken to the chat room view', null, { world }); 
    await And('I see "2 ACTIVE USERS" in the header', null, { world }); 
    await And('I see a system message containing "JOINED THE ROOM"', null, { world }); 
    await And('both the host and I are listed in the sidebar', null, { world }); 
  });

  test('Guest sees updated user count after joining', async ({ Given, When, Then, And, world }) => { 
    await Given('a host has created a room', null, { world }); 
    await When('a guest joins the room', null, { world }); 
    await Then('the host sees "2 ACTIVE USERS"', null, { world }); 
    await And('the guest sees "2 ACTIVE USERS"', null, { world }); 
  });

  test('Guest leaves the room and the host is notified', async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest clicks "Leave Room"', null, { world }); 
    await Then('the guest is returned to the landing page', null, { world }); 
    await And('the host sees a system message containing "LEFT THE ROOM"', null, { world }); 
    await And('the host sees "1 ACTIVE USERS"', null, { world }); 
  });

  test('Joining with a non-existent room code shows an error', async ({ Given, When, Then, And, world }) => { 
    await Given('I am on the landing page', null, { world }); 
    await When('I type "9999" in the room code input', null, { world }); 
    await And('I click "Join Room"', null, { world }); 
    await Then('I see the error banner "Room not found or host disconnected."', null, { world }); 
  });

  test('Host sends a message and guest receives it', async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host types "Olá do host!" in the message input and presses Enter', null, { world }); 
    await Then('the guest sees "Olá do host!" in the chat', null, { world }); 
    await And('the host sees "Olá do host!" in the chat with self-alignment', null, { world }); 
  });

  test('Guest sends a message and host receives it', async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest types "Olá do guest! 🚀" in the message input and presses Enter', null, { world }); 
    await Then('the host sees "Olá do guest! 🚀" in the chat', null, { world }); 
    await And('the guest sees "Olá do guest! 🚀" in the chat with self-alignment', null, { world }); 
  });

  test('Whitespace-only messages are not sent', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in a room', null, { world }); 
    await When('I type "   " in the message input and press Enter', null, { world }); 
    await Then('the send handler is not called', null, { world }); 
    await And('no new message appears in the chat', null, { world }); 
  });

  test('Empty messages state shows placeholder', async ({ Given, Then, world }) => { 
    await Given('I am in a room with no messages', null, { world }); 
    await Then('I see "No messages yet. Start the conversation!"', null, { world }); 
  });

  test('User renames themselves and the host sees the updated name', async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest clicks the edit icon next to their name in the sidebar', null, { world }); 
    await And('the guest types "GstRenome" and presses Enter', null, { world }); 
    await Then('the guest sidebar shows "GstRenome (You)"', null, { world }); 
    await And('the host sidebar shows "GstRenome" for that user', null, { world }); 
  });

  test('Editing name is cancelled when Escape is pressed', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in a room', null, { world }); 
    await When('I click the edit icon next to my name', null, { world }); 
    await And('I type "DraftName" in the name input', null, { world }); 
    await And('I press Escape', null, { world }); 
    await Then('my original name is still displayed', null, { world }); 
    await And('the rename callback is not called', null, { world }); 
  });

  test('Name is saved when the check button is clicked', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in a room', null, { world }); 
    await When('I click the edit icon next to my name', null, { world }); 
    await And('I type "SavedName" in the name input', null, { world }); 
    await And('I click the confirm button', null, { world }); 
    await Then('the rename callback is called with "SavedName"', null, { world }); 
  });

  test('Starting a call shows the call controls bar', async ({ Given, When, Then, And, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I click "Start Call"', null, { world }); 
    await Then('I see a system message "* STARTED A CALL"', null, { world }); 
    await And('I see the mute button in the call controls bar', null, { world }); 
    await And('I see the camera toggle button in the call controls bar', null, { world }); 
    await And('I see the end-call (PhoneOff) button in the call controls bar', null, { world }); 
    await And('I see a video tile with "Camera Off" text (no real camera in test environment)', null, { world }); 
  });

  test('Muting marks the user as muted in the sidebar', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in an active call', null, { world }); 
    await When('I click the mute button', null, { world }); 
    await Then('the mute icon appears next to my name in the sidebar', null, { world }); 
    await And('the mute button appears highlighted (active state)', null, { world }); 
  });

  test('Ending a call returns to the pre-call state', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in an active call', null, { world }); 
    await When('I click the end-call button', null, { world }); 
    await Then('the video grid is hidden', null, { world }); 
    await And('the "Start Call" button is visible again', null, { world }); 
  });

  test('Guest that did not start the call joins the call when toggling', async ({ Given, When, Then, And, world }) => { 
    await Given('a host has started a call', null, { world }); 
    await When('the guest clicks "Start Call"', null, { world }); 
    await Then('the guest sees their own video tile', null, { world }); 
    await And('the system message "* STARTED A CALL" appears for the guest', null, { world }); 
  });

  test('Error banner can be dismissed with the X button', async ({ Given, When, Then, And, world }) => { 
    await Given('I am in a room with an active error "Something went wrong"', null, { world }); 
    await When('I click the X button on the error banner', null, { world }); 
    await Then('the error banner disappears', null, { world }); 
    await And('the clear error callback is called', null, { world }); 
  });

  test('No error banner is shown when error is null', async ({ Given, Then, world }) => { 
    await Given('I am in a room with no error', null, { world }); 
    await Then('no error banner is visible', null, { world }); 
  });

  test('Third guest joins a room with two existing participants', { tag: ['@multi-user', '@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('a second guest joins the room', null, { world }); 
    await Then('all three participants see "3 ACTIVE USERS" in the header', null, { world }); 
    await And('all three participants are listed in the sidebar', null, { world }); 
  });

  test('Guest message is relayed by host to all other guests', { tag: ['@multi-user', '@slow'] }, async ({ Given, When, Then, world }) => { 
    await Given('a host and two guests are connected in the same room', null, { world }); 
    await When('the first guest types "hi everyone" in the message input and presses Enter', null, { world }); 
    await Then('the second guest also sees "hi everyone" in the chat', null, { world }); 
  });

  test('One guest leaves a multi-user room and the others are notified', { tag: ['@multi-user', '@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and two guests are connected in the same room', null, { world }); 
    await When('the first guest clicks "Leave Room"', null, { world }); 
    await Then('the host sees "2 ACTIVE USERS" in the header', null, { world }); 
    await And('the host sees a system message containing "LEFT THE ROOM"', null, { world }); 
  });

  test('Late joiner receives full room state including renamed room', { tag: ['@multi-user', '@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await And('the host has renamed the room to "Project Sync"', null, { world }); 
    await When('a second guest joins the room', null, { world }); 
    await Then('the second guest sees the room name as "Project Sync"', null, { world }); 
  });

  test('Starting a call when microphone permission is denied shows an error', { tag: ['@media-permissions'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await And('the browser has denied media access', null, { world }); 
    await When('I click "Start Call"', null, { world }); 
    await Then('I see the error banner "Could not access camera/mic."', null, { world }); 
    await And('the call controls bar is not shown', null, { world }); 
  });

  test('Camera hardware failure during an active call shows an error', { tag: ['@media-permissions'] }, async ({ Given, When, Then, world }) => { 
    await Given('I am in an active call', null, { world }); 
    await When('the camera hardware disconnects', null, { world }); 
    await Then('I see the error banner "Failed to access camera"', null, { world }); 
  });

  test('Video tile shows "Camera Off" placeholder when video is disabled', { tag: ['@video'] }, async ({ Given, Then, world }) => { 
    await Given('I am in an active call', null, { world }); 
    await Then('I see a video tile with "Camera Off" text', null, { world }); 
  });

  test('Remote user\'s video tile disappears when they end the call', { tag: ['@video', '@slow'] }, async ({ Given, When, Then, world }) => { 
    await Given('a host and a guest are in an active call', null, { world }); 
    await When('the guest ends the call', null, { world }); 
    await Then('the guest\'s video tile is removed from the host\'s video grid', null, { world }); 
  });

  test('Host closes the browser tab abruptly', { tag: ['@disconnection', '@slow'] }, async ({ Given, When, Then, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host closes the browser tab abruptly', null, { world }); 
    await Then('the guest sees the error "Disconnected from host."', null, { world }); 
  });

  test('Guest abruptly closes the browser tab', { tag: ['@disconnection', '@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest closes the browser tab abruptly', null, { world }); 
    await Then('the host sees a system message containing "LEFT THE ROOM"', null, { world }); 
    await And('the host sees "1 ACTIVE USERS" in the header', null, { world }); 
  });

  test('Page refresh mid-session returns user to landing page', { tag: ['@disconnection', '@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest refreshes the browser tab', null, { world }); 
    await Then('the guest sees the "PeerChat" heading', null, { world }); 
    await And('the host sees a system message containing "LEFT THE ROOM"', null, { world }); 
  });

  test('Rapid toggle of mute button does not desync UI from actual state', { tag: ['@race-condition'] }, async ({ Given, When, Then, world }) => { 
    await Given('I am in an active call', null, { world }); 
    await When('I click the mute button 5 times rapidly', null, { world }); 
    await Then('the final mute state is consistent between UI and audio track', null, { world }); 
  });

  test('Double-clicking "Start Call" does not create duplicate media connections', { tag: ['@race-condition'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I double-click "Start Call"', null, { world }); 
    await Then('only one video tile for myself appears', null, { world }); 
    await And('the call controls bar is visible', null, { world }); 
  });

  test('Guest does not see the room name edit icon in the sidebar', async ({ Given, Then, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await Then('the guest does not see the room name edit button', null, { world }); 
  });

  test('Host copies the room code to clipboard via the copy button', async ({ Given, When, Then, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I click the copy room code button', null, { world }); 
    await Then('a visual confirmation of the copy action is shown', null, { world }); 
  });

  test('Copied room code is exactly 4 digits', async ({ Given, When, Then, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I click the copy room code button', null, { world }); 
    await Then('the clipboard contains exactly 4 numeric characters', null, { world }); 
  });

  test('Message with HTML is rendered as plain text', { tag: ['@security'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host sends the message "<script>alert(\'xss\')</script>"', null, { world }); 
    await Then('the guest sees the raw text "<script>alert(\'xss\')</script>" in the chat', null, { world }); 
    await And('no script is executed in the browser', null, { world }); 
  });

  test('Very long message is displayed without breaking the layout', async ({ Given, When, Then, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host sends a 500-character message', null, { world }); 
    await Then('the message is fully displayed in the guest\'s chat', null, { world }); 
  });

  test('Chat auto-scrolls to the latest message', async ({ Given, When, Then, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the host sends 20 messages in sequence', null, { world }); 
    await Then('the last message is visible in the guest\'s chat', null, { world }); 
  });

  test('System messages are visually distinct from user messages', async ({ Given, When, Then, world }) => { 
    await Given('a host is in a room', null, { world }); 
    await When('a guest joins the room', null, { world }); 
    await Then('the system message has a different visual style than user messages', null, { world }); 
  });

  test('Returning to the tab after backgrounding shows current state', { tag: ['@slow'] }, async ({ Given, When, Then, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest backgrounds the tab and returns', null, { world }); 
    await Then('the guest can still send messages', null, { world }); 
  });

  test('Pressing Enter on the room code input triggers Join Room', async ({ Given, When, Then, And, world }) => { 
    await Given('I am on the landing page', null, { world }); 
    await When('I type "9999" in the room code input', null, { world }); 
    await And('I press Enter on the room code input', null, { world }); 
    await Then('I see the error banner "Room not found or host disconnected."', null, { world }); 
  });

  test('Empty name is not saved when editing', async ({ Given, When, Then, And, world }) => { 
    await Given('I am the host of a room', null, { world }); 
    await When('I click the edit icon next to my name', null, { world }); 
    await And('I clear the name input and press Enter', null, { world }); 
    await Then('my original name is still displayed', null, { world }); 
  });

  test('Username with emojis renders correctly in the sidebar', { tag: ['@slow'] }, async ({ Given, When, Then, And, world }) => { 
    await Given('a host and a guest are connected in the same room', null, { world }); 
    await When('the guest renames themselves to "Go 🚀🎯"', null, { world }); 
    await Then('the guest sidebar shows "Go 🚀🎯 (You)"', null, { world }); 
    await And('the host sidebar shows "Go 🚀🎯"', null, { world }); 
  });

});

// == technical section ==

test.beforeEach('BeforeEach Hooks', ({ $runScenarioHooks, world }) => $runScenarioHooks('before', { world }));

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('e2e/peerchat.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":10,"pickleLine":10,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":11,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then I see the \"PeerChat\" heading","stepMatchArguments":[{"group":{"start":10,"value":"\"PeerChat\"","children":[{"start":11,"value":"PeerChat","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":12,"keywordType":"Outcome","textWithKeyword":"And I see the tagline \"Serverless, private, ephemeral.\"","stepMatchArguments":[{"group":{"start":18,"value":"\"Serverless, private, ephemeral.\"","children":[{"start":19,"value":"Serverless, private, ephemeral.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":13,"keywordType":"Outcome","textWithKeyword":"And I see a \"Join a Room\" section with a 4-digit code input","stepMatchArguments":[{"group":{"start":8,"value":"\"Join a Room\"","children":[{"start":9,"value":"Join a Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":14,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"And I see a \"Host a Room\" section with an arrow button","stepMatchArguments":[{"group":{"start":8,"value":"\"Host a Room\"","children":[{"start":9,"value":"Host a Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":15,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"And the \"Join Room\" button is disabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Join Room\"","children":[{"start":5,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":16,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"And I see the footer \"Powered by PeerJS • End-to-End Client Side\"","stepMatchArguments":[{"group":{"start":17,"value":"\"Powered by PeerJS • End-to-End Client Side\"","children":[{"start":18,"value":"Powered by PeerJS • End-to-End Client Side","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":19,"pickleLine":18,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":20,"gherkinStepLine":19,"keywordType":"Action","textWithKeyword":"When I type \"12\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"12\"","children":[{"start":8,"value":"12","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":20,"keywordType":"Outcome","textWithKeyword":"Then the \"Join Room\" button is disabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Join Room\"","children":[{"start":5,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":21,"keywordType":"Action","textWithKeyword":"When I type \"1234\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"1234\"","children":[{"start":8,"value":"1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":23,"gherkinStepLine":22,"keywordType":"Outcome","textWithKeyword":"Then the \"Join Room\" button is enabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Join Room\"","children":[{"start":5,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":26,"pickleLine":24,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When I type \"12345\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"12345\"","children":[{"start":8,"value":"12345","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":26,"keywordType":"Outcome","textWithKeyword":"Then the input value is \"1234\"","stepMatchArguments":[{"group":{"start":19,"value":"\"1234\"","children":[{"start":20,"value":"1234","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":29,"gherkinStepLine":27,"keywordType":"Outcome","textWithKeyword":"And the \"Join Room\" button is enabled","stepMatchArguments":[{"group":{"start":4,"value":"\"Join Room\"","children":[{"start":5,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":32,"pickleLine":33,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":33,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When I click \"Host a Room\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Host a Room\"","children":[{"start":9,"value":"Host a Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":34,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then I am taken to the chat room view","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"And I see a 4-digit room code in the sidebar","stepMatchArguments":[]},{"pwStepLine":36,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"And I see \"1 ACTIVE USERS\" in the header","stepMatchArguments":[{"group":{"start":6,"value":"\"1 ACTIVE USERS\"","children":[{"start":7,"value":"1 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":38,"keywordType":"Outcome","textWithKeyword":"And my username is listed with \"(You)\" label in the sidebar","stepMatchArguments":[{"group":{"start":27,"value":"\"(You)\"","children":[{"start":28,"value":"(You)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":38,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"And I see a \"Start Call\" button","stepMatchArguments":[{"group":{"start":8,"value":"\"Start Call\"","children":[{"start":9,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":40,"keywordType":"Outcome","textWithKeyword":"And I see the footer \"End-to-End Encrypted P2P Connection\"","stepMatchArguments":[{"group":{"start":17,"value":"\"End-to-End Encrypted P2P Connection\"","children":[{"start":18,"value":"End-to-End Encrypted P2P Connection","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":42,"pickleLine":42,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":43,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":44,"keywordType":"Action","textWithKeyword":"When I click \"Leave Room\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Leave Room\"","children":[{"start":9,"value":"Leave Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":45,"keywordType":"Outcome","textWithKeyword":"Then I am returned to the landing page","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":46,"keywordType":"Outcome","textWithKeyword":"And I see the \"PeerChat\" heading","stepMatchArguments":[{"group":{"start":10,"value":"\"PeerChat\"","children":[{"start":11,"value":"PeerChat","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":49,"pickleLine":48,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":50,"gherkinStepLine":49,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When the host clicks the room name edit icon in the sidebar","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"And the host clears the field and types \"Sala de Testes E2E\"","stepMatchArguments":[{"group":{"start":36,"value":"\"Sala de Testes E2E\"","children":[{"start":37,"value":"Sala de Testes E2E","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":53,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"And the host presses Enter","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":53,"keywordType":"Outcome","textWithKeyword":"Then the host sees \"Sala de Testes E2E\" as the room name in the sidebar and header","stepMatchArguments":[{"group":{"start":14,"value":"\"Sala de Testes E2E\"","children":[{"start":15,"value":"Sala de Testes E2E","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":55,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"And the guest also sees \"Sala de Testes E2E\" as the room name in real-time","stepMatchArguments":[{"group":{"start":20,"value":"\"Sala de Testes E2E\"","children":[{"start":21,"value":"Sala de Testes E2E","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":58,"pickleLine":56,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":59,"gherkinStepLine":57,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then there is no room code input visible on the screen","stepMatchArguments":[]}]},
  {"pwTestLine":63,"pickleLine":64,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given a host has created a room with code \"8414\"","stepMatchArguments":[{"group":{"start":36,"value":"\"8414\"","children":[{"start":37,"value":"8414","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":65,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"And I am on the landing page as a guest","stepMatchArguments":[]},{"pwStepLine":66,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When I type \"8414\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"8414\"","children":[{"start":8,"value":"8414","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":67,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"And I click \"Join Room\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Join Room\"","children":[{"start":9,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":68,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"Then I am taken to the chat room view","stepMatchArguments":[]},{"pwStepLine":69,"gherkinStepLine":70,"keywordType":"Outcome","textWithKeyword":"And I see \"2 ACTIVE USERS\" in the header","stepMatchArguments":[{"group":{"start":6,"value":"\"2 ACTIVE USERS\"","children":[{"start":7,"value":"2 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":70,"gherkinStepLine":71,"keywordType":"Outcome","textWithKeyword":"And I see a system message containing \"JOINED THE ROOM\"","stepMatchArguments":[{"group":{"start":34,"value":"\"JOINED THE ROOM\"","children":[{"start":35,"value":"JOINED THE ROOM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"And both the host and I are listed in the sidebar","stepMatchArguments":[]}]},
  {"pwTestLine":74,"pickleLine":74,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":75,"gherkinStepLine":75,"keywordType":"Context","textWithKeyword":"Given a host has created a room","stepMatchArguments":[]},{"pwStepLine":76,"gherkinStepLine":76,"keywordType":"Action","textWithKeyword":"When a guest joins the room","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":77,"keywordType":"Outcome","textWithKeyword":"Then the host sees \"2 ACTIVE USERS\"","stepMatchArguments":[{"group":{"start":14,"value":"\"2 ACTIVE USERS\"","children":[{"start":15,"value":"2 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":78,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"And the guest sees \"2 ACTIVE USERS\"","stepMatchArguments":[{"group":{"start":15,"value":"\"2 ACTIVE USERS\"","children":[{"start":16,"value":"2 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":81,"pickleLine":80,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":82,"gherkinStepLine":81,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":82,"keywordType":"Action","textWithKeyword":"When the guest clicks \"Leave Room\"","stepMatchArguments":[{"group":{"start":17,"value":"\"Leave Room\"","children":[{"start":18,"value":"Leave Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":84,"gherkinStepLine":83,"keywordType":"Outcome","textWithKeyword":"Then the guest is returned to the landing page","stepMatchArguments":[]},{"pwStepLine":85,"gherkinStepLine":84,"keywordType":"Outcome","textWithKeyword":"And the host sees a system message containing \"LEFT THE ROOM\"","stepMatchArguments":[{"group":{"start":42,"value":"\"LEFT THE ROOM\"","children":[{"start":43,"value":"LEFT THE ROOM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":86,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"And the host sees \"1 ACTIVE USERS\"","stepMatchArguments":[{"group":{"start":14,"value":"\"1 ACTIVE USERS\"","children":[{"start":15,"value":"1 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":89,"pickleLine":87,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":90,"gherkinStepLine":88,"keywordType":"Context","textWithKeyword":"Given I am on the landing page","stepMatchArguments":[]},{"pwStepLine":91,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"When I type \"9999\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"9999\"","children":[{"start":8,"value":"9999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":92,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"And I click \"Join Room\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Join Room\"","children":[{"start":9,"value":"Join Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":93,"gherkinStepLine":91,"keywordType":"Outcome","textWithKeyword":"Then I see the error banner \"Room not found or host disconnected.\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Room not found or host disconnected.\"","children":[{"start":24,"value":"Room not found or host disconnected.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":96,"pickleLine":97,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":97,"gherkinStepLine":98,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":99,"keywordType":"Action","textWithKeyword":"When the host types \"Olá do host!\" in the message input and presses Enter","stepMatchArguments":[{"group":{"start":15,"value":"\"Olá do host!\"","children":[{"start":16,"value":"Olá do host!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":99,"gherkinStepLine":100,"keywordType":"Outcome","textWithKeyword":"Then the guest sees \"Olá do host!\" in the chat","stepMatchArguments":[{"group":{"start":15,"value":"\"Olá do host!\"","children":[{"start":16,"value":"Olá do host!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":100,"gherkinStepLine":101,"keywordType":"Outcome","textWithKeyword":"And the host sees \"Olá do host!\" in the chat with self-alignment","stepMatchArguments":[{"group":{"start":14,"value":"\"Olá do host!\"","children":[{"start":15,"value":"Olá do host!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":103,"pickleLine":103,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":104,"gherkinStepLine":104,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":105,"gherkinStepLine":105,"keywordType":"Action","textWithKeyword":"When the guest types \"Olá do guest! 🚀\" in the message input and presses Enter","stepMatchArguments":[{"group":{"start":16,"value":"\"Olá do guest! 🚀\"","children":[{"start":17,"value":"Olá do guest! 🚀","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":106,"gherkinStepLine":106,"keywordType":"Outcome","textWithKeyword":"Then the host sees \"Olá do guest! 🚀\" in the chat","stepMatchArguments":[{"group":{"start":14,"value":"\"Olá do guest! 🚀\"","children":[{"start":15,"value":"Olá do guest! 🚀","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":107,"gherkinStepLine":107,"keywordType":"Outcome","textWithKeyword":"And the guest sees \"Olá do guest! 🚀\" in the chat with self-alignment","stepMatchArguments":[{"group":{"start":15,"value":"\"Olá do guest! 🚀\"","children":[{"start":16,"value":"Olá do guest! 🚀","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":110,"pickleLine":109,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":111,"gherkinStepLine":110,"keywordType":"Context","textWithKeyword":"Given I am in a room","stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":111,"keywordType":"Action","textWithKeyword":"When I type \"   \" in the message input and press Enter","stepMatchArguments":[{"group":{"start":7,"value":"\"   \"","children":[{"start":8,"value":"   ","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":113,"gherkinStepLine":112,"keywordType":"Outcome","textWithKeyword":"Then the send handler is not called","stepMatchArguments":[]},{"pwStepLine":114,"gherkinStepLine":113,"keywordType":"Outcome","textWithKeyword":"And no new message appears in the chat","stepMatchArguments":[]}]},
  {"pwTestLine":117,"pickleLine":115,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":118,"gherkinStepLine":116,"keywordType":"Context","textWithKeyword":"Given I am in a room with no messages","stepMatchArguments":[]},{"pwStepLine":119,"gherkinStepLine":117,"keywordType":"Outcome","textWithKeyword":"Then I see \"No messages yet. Start the conversation!\"","stepMatchArguments":[{"group":{"start":6,"value":"\"No messages yet. Start the conversation!\"","children":[{"start":7,"value":"No messages yet. Start the conversation!","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":122,"pickleLine":123,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":123,"gherkinStepLine":124,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":125,"keywordType":"Action","textWithKeyword":"When the guest clicks the edit icon next to their name in the sidebar","stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":126,"keywordType":"Action","textWithKeyword":"And the guest types \"GstRenome\" and presses Enter","stepMatchArguments":[{"group":{"start":16,"value":"\"GstRenome\"","children":[{"start":17,"value":"GstRenome","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":126,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"Then the guest sidebar shows \"GstRenome (You)\"","stepMatchArguments":[{"group":{"start":24,"value":"\"GstRenome (You)\"","children":[{"start":25,"value":"GstRenome (You)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":127,"gherkinStepLine":128,"keywordType":"Outcome","textWithKeyword":"And the host sidebar shows \"GstRenome\" for that user","stepMatchArguments":[{"group":{"start":23,"value":"\"GstRenome\"","children":[{"start":24,"value":"GstRenome","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":130,"pickleLine":130,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":131,"gherkinStepLine":131,"keywordType":"Context","textWithKeyword":"Given I am in a room","stepMatchArguments":[]},{"pwStepLine":132,"gherkinStepLine":132,"keywordType":"Action","textWithKeyword":"When I click the edit icon next to my name","stepMatchArguments":[]},{"pwStepLine":133,"gherkinStepLine":133,"keywordType":"Action","textWithKeyword":"And I type \"DraftName\" in the name input","stepMatchArguments":[{"group":{"start":7,"value":"\"DraftName\"","children":[{"start":8,"value":"DraftName","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":134,"gherkinStepLine":134,"keywordType":"Action","textWithKeyword":"And I press Escape","stepMatchArguments":[]},{"pwStepLine":135,"gherkinStepLine":135,"keywordType":"Outcome","textWithKeyword":"Then my original name is still displayed","stepMatchArguments":[]},{"pwStepLine":136,"gherkinStepLine":136,"keywordType":"Outcome","textWithKeyword":"And the rename callback is not called","stepMatchArguments":[]}]},
  {"pwTestLine":139,"pickleLine":138,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":140,"gherkinStepLine":139,"keywordType":"Context","textWithKeyword":"Given I am in a room","stepMatchArguments":[]},{"pwStepLine":141,"gherkinStepLine":140,"keywordType":"Action","textWithKeyword":"When I click the edit icon next to my name","stepMatchArguments":[]},{"pwStepLine":142,"gherkinStepLine":141,"keywordType":"Action","textWithKeyword":"And I type \"SavedName\" in the name input","stepMatchArguments":[{"group":{"start":7,"value":"\"SavedName\"","children":[{"start":8,"value":"SavedName","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":143,"gherkinStepLine":142,"keywordType":"Action","textWithKeyword":"And I click the confirm button","stepMatchArguments":[]},{"pwStepLine":144,"gherkinStepLine":143,"keywordType":"Outcome","textWithKeyword":"Then the rename callback is called with \"SavedName\"","stepMatchArguments":[{"group":{"start":35,"value":"\"SavedName\"","children":[{"start":36,"value":"SavedName","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":147,"pickleLine":149,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":148,"gherkinStepLine":150,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":149,"gherkinStepLine":151,"keywordType":"Action","textWithKeyword":"When I click \"Start Call\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Start Call\"","children":[{"start":9,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":150,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"Then I see a system message \"* STARTED A CALL\"","stepMatchArguments":[{"group":{"start":23,"value":"\"* STARTED A CALL\"","children":[{"start":24,"value":"* STARTED A CALL","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":151,"gherkinStepLine":153,"keywordType":"Outcome","textWithKeyword":"And I see the mute button in the call controls bar","stepMatchArguments":[]},{"pwStepLine":152,"gherkinStepLine":154,"keywordType":"Outcome","textWithKeyword":"And I see the camera toggle button in the call controls bar","stepMatchArguments":[]},{"pwStepLine":153,"gherkinStepLine":155,"keywordType":"Outcome","textWithKeyword":"And I see the end-call (PhoneOff) button in the call controls bar","stepMatchArguments":[]},{"pwStepLine":154,"gherkinStepLine":156,"keywordType":"Outcome","textWithKeyword":"And I see a video tile with \"Camera Off\" text (no real camera in test environment)","stepMatchArguments":[{"group":{"start":25,"value":"Camera Off","children":[]}}]}]},
  {"pwTestLine":157,"pickleLine":158,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":158,"gherkinStepLine":159,"keywordType":"Context","textWithKeyword":"Given I am in an active call","stepMatchArguments":[]},{"pwStepLine":159,"gherkinStepLine":160,"keywordType":"Action","textWithKeyword":"When I click the mute button","stepMatchArguments":[]},{"pwStepLine":160,"gherkinStepLine":161,"keywordType":"Outcome","textWithKeyword":"Then the mute icon appears next to my name in the sidebar","stepMatchArguments":[]},{"pwStepLine":161,"gherkinStepLine":162,"keywordType":"Outcome","textWithKeyword":"And the mute button appears highlighted (active state)","stepMatchArguments":[]}]},
  {"pwTestLine":164,"pickleLine":164,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":165,"gherkinStepLine":165,"keywordType":"Context","textWithKeyword":"Given I am in an active call","stepMatchArguments":[]},{"pwStepLine":166,"gherkinStepLine":166,"keywordType":"Action","textWithKeyword":"When I click the end-call button","stepMatchArguments":[]},{"pwStepLine":167,"gherkinStepLine":167,"keywordType":"Outcome","textWithKeyword":"Then the video grid is hidden","stepMatchArguments":[]},{"pwStepLine":168,"gherkinStepLine":168,"keywordType":"Outcome","textWithKeyword":"And the \"Start Call\" button is visible again","stepMatchArguments":[{"group":{"start":4,"value":"\"Start Call\"","children":[{"start":5,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":171,"pickleLine":170,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":172,"gherkinStepLine":171,"keywordType":"Context","textWithKeyword":"Given a host has started a call","stepMatchArguments":[]},{"pwStepLine":173,"gherkinStepLine":172,"keywordType":"Action","textWithKeyword":"When the guest clicks \"Start Call\"","stepMatchArguments":[{"group":{"start":17,"value":"\"Start Call\"","children":[{"start":18,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":174,"gherkinStepLine":173,"keywordType":"Outcome","textWithKeyword":"Then the guest sees their own video tile","stepMatchArguments":[]},{"pwStepLine":175,"gherkinStepLine":174,"keywordType":"Outcome","textWithKeyword":"And the system message \"* STARTED A CALL\" appears for the guest","stepMatchArguments":[{"group":{"start":19,"value":"\"* STARTED A CALL\"","children":[{"start":20,"value":"* STARTED A CALL","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":178,"pickleLine":180,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":179,"gherkinStepLine":181,"keywordType":"Context","textWithKeyword":"Given I am in a room with an active error \"Something went wrong\"","stepMatchArguments":[{"group":{"start":36,"value":"\"Something went wrong\"","children":[{"start":37,"value":"Something went wrong","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":180,"gherkinStepLine":182,"keywordType":"Action","textWithKeyword":"When I click the X button on the error banner","stepMatchArguments":[]},{"pwStepLine":181,"gherkinStepLine":183,"keywordType":"Outcome","textWithKeyword":"Then the error banner disappears","stepMatchArguments":[]},{"pwStepLine":182,"gherkinStepLine":184,"keywordType":"Outcome","textWithKeyword":"And the clear error callback is called","stepMatchArguments":[]}]},
  {"pwTestLine":185,"pickleLine":186,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":186,"gherkinStepLine":187,"keywordType":"Context","textWithKeyword":"Given I am in a room with no error","stepMatchArguments":[]},{"pwStepLine":187,"gherkinStepLine":188,"keywordType":"Outcome","textWithKeyword":"Then no error banner is visible","stepMatchArguments":[]}]},
  {"pwTestLine":190,"pickleLine":195,"slow":true,"tags":["@multi-user","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":191,"gherkinStepLine":196,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":192,"gherkinStepLine":197,"keywordType":"Action","textWithKeyword":"When a second guest joins the room","stepMatchArguments":[]},{"pwStepLine":193,"gherkinStepLine":198,"keywordType":"Outcome","textWithKeyword":"Then all three participants see \"3 ACTIVE USERS\" in the header","stepMatchArguments":[{"group":{"start":27,"value":"\"3 ACTIVE USERS\"","children":[{"start":28,"value":"3 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":194,"gherkinStepLine":199,"keywordType":"Outcome","textWithKeyword":"And all three participants are listed in the sidebar","stepMatchArguments":[]}]},
  {"pwTestLine":197,"pickleLine":202,"slow":true,"tags":["@multi-user","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":198,"gherkinStepLine":203,"keywordType":"Context","textWithKeyword":"Given a host and two guests are connected in the same room","stepMatchArguments":[]},{"pwStepLine":199,"gherkinStepLine":204,"keywordType":"Action","textWithKeyword":"When the first guest types \"hi everyone\" in the message input and presses Enter","stepMatchArguments":[{"group":{"start":22,"value":"\"hi everyone\"","children":[{"start":23,"value":"hi everyone","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":200,"gherkinStepLine":205,"keywordType":"Outcome","textWithKeyword":"Then the second guest also sees \"hi everyone\" in the chat","stepMatchArguments":[{"group":{"start":27,"value":"\"hi everyone\"","children":[{"start":28,"value":"hi everyone","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":203,"pickleLine":208,"slow":true,"tags":["@multi-user","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":204,"gherkinStepLine":209,"keywordType":"Context","textWithKeyword":"Given a host and two guests are connected in the same room","stepMatchArguments":[]},{"pwStepLine":205,"gherkinStepLine":210,"keywordType":"Action","textWithKeyword":"When the first guest clicks \"Leave Room\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Leave Room\"","children":[{"start":24,"value":"Leave Room","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":206,"gherkinStepLine":211,"keywordType":"Outcome","textWithKeyword":"Then the host sees \"2 ACTIVE USERS\" in the header","stepMatchArguments":[{"group":{"start":14,"value":"\"2 ACTIVE USERS\"","children":[{"start":15,"value":"2 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":207,"gherkinStepLine":212,"keywordType":"Outcome","textWithKeyword":"And the host sees a system message containing \"LEFT THE ROOM\"","stepMatchArguments":[{"group":{"start":42,"value":"\"LEFT THE ROOM\"","children":[{"start":43,"value":"LEFT THE ROOM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":210,"pickleLine":215,"slow":true,"tags":["@multi-user","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":211,"gherkinStepLine":216,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":212,"gherkinStepLine":217,"keywordType":"Context","textWithKeyword":"And the host has renamed the room to \"Project Sync\"","stepMatchArguments":[{"group":{"start":33,"value":"\"Project Sync\"","children":[{"start":34,"value":"Project Sync","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":213,"gherkinStepLine":218,"keywordType":"Action","textWithKeyword":"When a second guest joins the room","stepMatchArguments":[]},{"pwStepLine":214,"gherkinStepLine":219,"keywordType":"Outcome","textWithKeyword":"Then the second guest sees the room name as \"Project Sync\"","stepMatchArguments":[{"group":{"start":39,"value":"\"Project Sync\"","children":[{"start":40,"value":"Project Sync","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":217,"pickleLine":226,"tags":["@media-permissions"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":218,"gherkinStepLine":227,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":219,"gherkinStepLine":228,"keywordType":"Context","textWithKeyword":"And the browser has denied media access","stepMatchArguments":[]},{"pwStepLine":220,"gherkinStepLine":229,"keywordType":"Action","textWithKeyword":"When I click \"Start Call\"","stepMatchArguments":[{"group":{"start":8,"value":"\"Start Call\"","children":[{"start":9,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":221,"gherkinStepLine":230,"keywordType":"Outcome","textWithKeyword":"Then I see the error banner \"Could not access camera/mic.\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Could not access camera/mic.\"","children":[{"start":24,"value":"Could not access camera/mic.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":222,"gherkinStepLine":231,"keywordType":"Outcome","textWithKeyword":"And the call controls bar is not shown","stepMatchArguments":[]}]},
  {"pwTestLine":225,"pickleLine":234,"tags":["@media-permissions"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":226,"gherkinStepLine":235,"keywordType":"Context","textWithKeyword":"Given I am in an active call","stepMatchArguments":[]},{"pwStepLine":227,"gherkinStepLine":236,"keywordType":"Action","textWithKeyword":"When the camera hardware disconnects","stepMatchArguments":[]},{"pwStepLine":228,"gherkinStepLine":237,"keywordType":"Outcome","textWithKeyword":"Then I see the error banner \"Failed to access camera\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Failed to access camera\"","children":[{"start":24,"value":"Failed to access camera","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":231,"pickleLine":244,"tags":["@video"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":232,"gherkinStepLine":245,"keywordType":"Context","textWithKeyword":"Given I am in an active call","stepMatchArguments":[]},{"pwStepLine":233,"gherkinStepLine":246,"keywordType":"Outcome","textWithKeyword":"Then I see a video tile with \"Camera Off\" text","stepMatchArguments":[{"group":{"start":25,"value":"Camera Off","children":[]}}]}]},
  {"pwTestLine":236,"pickleLine":249,"slow":true,"tags":["@video","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":237,"gherkinStepLine":250,"keywordType":"Context","textWithKeyword":"Given a host and a guest are in an active call","stepMatchArguments":[]},{"pwStepLine":238,"gherkinStepLine":251,"keywordType":"Action","textWithKeyword":"When the guest ends the call","stepMatchArguments":[]},{"pwStepLine":239,"gherkinStepLine":252,"keywordType":"Outcome","textWithKeyword":"Then the guest's video tile is removed from the host's video grid","stepMatchArguments":[]}]},
  {"pwTestLine":242,"pickleLine":259,"slow":true,"tags":["@disconnection","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":243,"gherkinStepLine":260,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":244,"gherkinStepLine":261,"keywordType":"Action","textWithKeyword":"When the host closes the browser tab abruptly","stepMatchArguments":[]},{"pwStepLine":245,"gherkinStepLine":262,"keywordType":"Outcome","textWithKeyword":"Then the guest sees the error \"Disconnected from host.\"","stepMatchArguments":[{"group":{"start":25,"value":"\"Disconnected from host.\"","children":[{"start":26,"value":"Disconnected from host.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":248,"pickleLine":265,"slow":true,"tags":["@disconnection","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":249,"gherkinStepLine":266,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":250,"gherkinStepLine":267,"keywordType":"Action","textWithKeyword":"When the guest closes the browser tab abruptly","stepMatchArguments":[]},{"pwStepLine":251,"gherkinStepLine":268,"keywordType":"Outcome","textWithKeyword":"Then the host sees a system message containing \"LEFT THE ROOM\"","stepMatchArguments":[{"group":{"start":42,"value":"\"LEFT THE ROOM\"","children":[{"start":43,"value":"LEFT THE ROOM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":252,"gherkinStepLine":269,"keywordType":"Outcome","textWithKeyword":"And the host sees \"1 ACTIVE USERS\" in the header","stepMatchArguments":[{"group":{"start":14,"value":"\"1 ACTIVE USERS\"","children":[{"start":15,"value":"1 ACTIVE USERS","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":255,"pickleLine":272,"slow":true,"tags":["@disconnection","@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":256,"gherkinStepLine":273,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":257,"gherkinStepLine":274,"keywordType":"Action","textWithKeyword":"When the guest refreshes the browser tab","stepMatchArguments":[]},{"pwStepLine":258,"gherkinStepLine":275,"keywordType":"Outcome","textWithKeyword":"Then the guest sees the \"PeerChat\" heading","stepMatchArguments":[{"group":{"start":19,"value":"\"PeerChat\"","children":[{"start":20,"value":"PeerChat","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":259,"gherkinStepLine":276,"keywordType":"Outcome","textWithKeyword":"And the host sees a system message containing \"LEFT THE ROOM\"","stepMatchArguments":[{"group":{"start":42,"value":"\"LEFT THE ROOM\"","children":[{"start":43,"value":"LEFT THE ROOM","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":262,"pickleLine":283,"tags":["@race-condition"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":263,"gherkinStepLine":284,"keywordType":"Context","textWithKeyword":"Given I am in an active call","stepMatchArguments":[]},{"pwStepLine":264,"gherkinStepLine":285,"keywordType":"Action","textWithKeyword":"When I click the mute button 5 times rapidly","stepMatchArguments":[]},{"pwStepLine":265,"gherkinStepLine":286,"keywordType":"Outcome","textWithKeyword":"Then the final mute state is consistent between UI and audio track","stepMatchArguments":[]}]},
  {"pwTestLine":268,"pickleLine":289,"tags":["@race-condition"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":269,"gherkinStepLine":290,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":270,"gherkinStepLine":291,"keywordType":"Action","textWithKeyword":"When I double-click \"Start Call\"","stepMatchArguments":[{"group":{"start":15,"value":"\"Start Call\"","children":[{"start":16,"value":"Start Call","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":271,"gherkinStepLine":292,"keywordType":"Outcome","textWithKeyword":"Then only one video tile for myself appears","stepMatchArguments":[]},{"pwStepLine":272,"gherkinStepLine":293,"keywordType":"Outcome","textWithKeyword":"And the call controls bar is visible","stepMatchArguments":[]}]},
  {"pwTestLine":275,"pickleLine":299,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":276,"gherkinStepLine":300,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":277,"gherkinStepLine":301,"keywordType":"Outcome","textWithKeyword":"Then the guest does not see the room name edit button","stepMatchArguments":[]}]},
  {"pwTestLine":280,"pickleLine":307,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":281,"gherkinStepLine":308,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":282,"gherkinStepLine":309,"keywordType":"Action","textWithKeyword":"When I click the copy room code button","stepMatchArguments":[]},{"pwStepLine":283,"gherkinStepLine":310,"keywordType":"Outcome","textWithKeyword":"Then a visual confirmation of the copy action is shown","stepMatchArguments":[]}]},
  {"pwTestLine":286,"pickleLine":312,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":287,"gherkinStepLine":313,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":288,"gherkinStepLine":314,"keywordType":"Action","textWithKeyword":"When I click the copy room code button","stepMatchArguments":[]},{"pwStepLine":289,"gherkinStepLine":315,"keywordType":"Outcome","textWithKeyword":"Then the clipboard contains exactly 4 numeric characters","stepMatchArguments":[]}]},
  {"pwTestLine":292,"pickleLine":322,"tags":["@security"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":293,"gherkinStepLine":323,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":294,"gherkinStepLine":324,"keywordType":"Action","textWithKeyword":"When the host sends the message \"<script>alert('xss')</script>\"","stepMatchArguments":[{"group":{"start":27,"value":"\"<script>alert('xss')</script>\"","children":[{"start":28,"value":"<script>alert('xss')</script>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":295,"gherkinStepLine":325,"keywordType":"Outcome","textWithKeyword":"Then the guest sees the raw text \"<script>alert('xss')</script>\" in the chat","stepMatchArguments":[{"group":{"start":28,"value":"\"<script>alert('xss')</script>\"","children":[{"start":29,"value":"<script>alert('xss')</script>","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":296,"gherkinStepLine":326,"keywordType":"Outcome","textWithKeyword":"And no script is executed in the browser","stepMatchArguments":[]}]},
  {"pwTestLine":299,"pickleLine":332,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":300,"gherkinStepLine":333,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":301,"gherkinStepLine":334,"keywordType":"Action","textWithKeyword":"When the host sends a 500-character message","stepMatchArguments":[]},{"pwStepLine":302,"gherkinStepLine":335,"keywordType":"Outcome","textWithKeyword":"Then the message is fully displayed in the guest's chat","stepMatchArguments":[]}]},
  {"pwTestLine":305,"pickleLine":337,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":306,"gherkinStepLine":338,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":307,"gherkinStepLine":339,"keywordType":"Action","textWithKeyword":"When the host sends 20 messages in sequence","stepMatchArguments":[]},{"pwStepLine":308,"gherkinStepLine":340,"keywordType":"Outcome","textWithKeyword":"Then the last message is visible in the guest's chat","stepMatchArguments":[]}]},
  {"pwTestLine":311,"pickleLine":342,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":312,"gherkinStepLine":343,"keywordType":"Context","textWithKeyword":"Given a host is in a room","stepMatchArguments":[]},{"pwStepLine":313,"gherkinStepLine":344,"keywordType":"Action","textWithKeyword":"When a guest joins the room","stepMatchArguments":[]},{"pwStepLine":314,"gherkinStepLine":345,"keywordType":"Outcome","textWithKeyword":"Then the system message has a different visual style than user messages","stepMatchArguments":[]}]},
  {"pwTestLine":317,"pickleLine":352,"slow":true,"tags":["@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":318,"gherkinStepLine":353,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":319,"gherkinStepLine":354,"keywordType":"Action","textWithKeyword":"When the guest backgrounds the tab and returns","stepMatchArguments":[]},{"pwStepLine":320,"gherkinStepLine":355,"keywordType":"Outcome","textWithKeyword":"Then the guest can still send messages","stepMatchArguments":[]}]},
  {"pwTestLine":323,"pickleLine":361,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":324,"gherkinStepLine":362,"keywordType":"Context","textWithKeyword":"Given I am on the landing page","stepMatchArguments":[]},{"pwStepLine":325,"gherkinStepLine":363,"keywordType":"Action","textWithKeyword":"When I type \"9999\" in the room code input","stepMatchArguments":[{"group":{"start":7,"value":"\"9999\"","children":[{"start":8,"value":"9999","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":326,"gherkinStepLine":364,"keywordType":"Action","textWithKeyword":"And I press Enter on the room code input","stepMatchArguments":[]},{"pwStepLine":327,"gherkinStepLine":365,"keywordType":"Outcome","textWithKeyword":"Then I see the error banner \"Room not found or host disconnected.\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Room not found or host disconnected.\"","children":[{"start":24,"value":"Room not found or host disconnected.","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":330,"pickleLine":367,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":331,"gherkinStepLine":368,"keywordType":"Context","textWithKeyword":"Given I am the host of a room","stepMatchArguments":[]},{"pwStepLine":332,"gherkinStepLine":369,"keywordType":"Action","textWithKeyword":"When I click the edit icon next to my name","stepMatchArguments":[]},{"pwStepLine":333,"gherkinStepLine":370,"keywordType":"Action","textWithKeyword":"And I clear the name input and press Enter","stepMatchArguments":[]},{"pwStepLine":334,"gherkinStepLine":371,"keywordType":"Outcome","textWithKeyword":"Then my original name is still displayed","stepMatchArguments":[]}]},
  {"pwTestLine":337,"pickleLine":374,"slow":true,"tags":["@slow"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given the PeerChat application is running at \"http://localhost:5174\"","isBg":true,"stepMatchArguments":[{"group":{"start":39,"value":"\"http://localhost:5174\"","children":[{"start":40,"value":"http://localhost:5174","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":338,"gherkinStepLine":375,"keywordType":"Context","textWithKeyword":"Given a host and a guest are connected in the same room","stepMatchArguments":[]},{"pwStepLine":339,"gherkinStepLine":376,"keywordType":"Action","textWithKeyword":"When the guest renames themselves to \"Go 🚀🎯\"","stepMatchArguments":[{"group":{"start":32,"value":"\"Go 🚀🎯\"","children":[{"start":33,"value":"Go 🚀🎯","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":340,"gherkinStepLine":377,"keywordType":"Outcome","textWithKeyword":"Then the guest sidebar shows \"Go 🚀🎯 (You)\"","stepMatchArguments":[{"group":{"start":24,"value":"\"Go 🚀🎯 (You)\"","children":[{"start":25,"value":"Go 🚀🎯 (You)","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":341,"gherkinStepLine":378,"keywordType":"Outcome","textWithKeyword":"And the host sidebar shows \"Go 🚀🎯\"","stepMatchArguments":[{"group":{"start":23,"value":"\"Go 🚀🎯\"","children":[{"start":24,"value":"Go 🚀🎯","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end